# Travis CI script
language: c

os:
- linux
- osx

sudo: false

env:
- BUILD_TYPE=default
- BUILD_TYPE=android
#- BUILD_TYPE=check-py
#- BUILD_TYPE=cmake

addons:
  apt:
    packages:
    - valgrind

before_install:
- if [ $TRAVIS_OS_NAME == "osx" ] ; then brew update; brew install binutils valgrind ; fi

# Build and check this project according to the BUILD_TYPE
script: ./ci_build.sh
